spring:
  application:
    name: finance
  datasource:
    url: jdbc:mysql://localhost:3306/finance
    username: root
    password: jain@2020
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none  # Disable Hibernate DDL since we're using Flyway
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

# Finance Application Configuration
finance:
  transaction:
    # Maximum transaction limits (system-wide)
    max-transfer-limit: 1000000.00
    max-deposit-limit: 500000.00
    max-withdraw-limit: 100000.00
    
    # Default daily limits (per account, per transaction type)
    default-daily-limit: 50000.00
    default-daily-transaction-count: 50
